### ISSUE TITLE
Issues on new scaffold

### ISSUE THREAD

**Issue by Antonio-Laguna** [10up/10up-toolkit#443]
### Describe the bug

When using `npx 10up-toolkit project init` as suggested on the README, if you install dependencies and just try to build (no changes), you get the following error on both the plugin and the theme:

```
ERROR in Input buffer contains unsupported image format

ERROR in Input buffer contains unsupported image format

ERROR in Input buffer contains unsupported image format

webpack 5.97.0 compiled with 3 errors in 490 ms
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path /Users/alaguna/Projects/acretest/mu-plugins/acre-plugin
npm error workspace acre-plugin@1.0.0
npm error location /Users/alaguna/Projects/acretest/mu-plugins/acre-plugin
npm error command failed
npm error command sh -c 10up-toolkit build
```

Additionally, `admin-style` is tried to be load but it's not generated and there's another error related to editor-style-overrides.

See below:

<img width="1376" alt="Image" src="https://github.com/user-attachments/assets/6624998d-aea1-4676-83dd-3b70923b4f26" />

### Steps to Reproduce

1. Create a project with `npx 10up-toolkit project init`
2. Try to build

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by fabiankaegy** [comment]
CC: @tlovett1

**Comment by colorful-tones** [comment]
I'm not able to even install with `npx 10up-toolkit project init`, as I get dependency resolution errors. I'm happy to open a separate issue though, as it seems initial reporter was able to get things installed and not able to run build.

<details>
<summary>Expand for full npm error log output</summary>

```bash
❯ npx 10up-toolkit project init
Need to install the following packages:
10up-toolkit@6.4.1
Ok to proceed? (y) y

npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: eslint-plugin-jest@29.0.1
npm error Found: @typescript-eslint/eslint-plugin@6.21.0
npm error node_modules/@typescript-eslint/eslint-plugin
npm error   @typescript-eslint/eslint-plugin@"^6.17.0" from 10up-toolkit@6.4.1
npm error   node_modules/10up-toolkit
npm error     10up-toolkit@"6.4.1" from the root project
npm error   @typescript-eslint/eslint-plugin@"^6.4.1" from @wordpress/eslint-plugin@17.13.0
npm error   node_modules/@wordpress/eslint-plugin
npm error     @wordpress/eslint-plugin@"^17.5.0" from 10up-toolkit@6.4.1
npm error     node_modules/10up-toolkit
npm error       10up-toolkit@"6.4.1" from the root project
npm error     peerOptional @wordpress/eslint-plugin@"^17.5.0" from @10up/eslint-config@4.1.2
npm error     node_modules/@10up/eslint-config
npm error       peer @10up/eslint-config@">=4.1.1" from 10up-toolkit@6.4.1
npm error       node_modules/10up-toolkit
npm error         10up-toolkit@"6.4.1" from the root project
npm error   1 more (eslint-plugin-jest)
npm error
npm error Could not resolve dependency:
npm error peerOptional @typescript-eslint/eslint-plugin@"^8.0.0" from eslint-plugin-jest@29.0.1
npm error node_modules/eslint-plugin-jest
npm error   peer eslint-plugin-jest@">=27.6.1" from @10up/eslint-config@4.1.2
npm error   node_modules/@10up/eslint-config
npm error     peer @10up/eslint-config@">=4.1.1" from 10up-toolkit@6.4.1
npm error     node_modules/10up-toolkit
npm error       10up-toolkit@"6.4.1" from the root project
npm error   peerOptional eslint-plugin-jest@">=25" from eslint-plugin-playwright@0.15.3
npm error   node_modules/eslint-plugin-playwright
npm error     eslint-plugin-playwright@"^0.15.3" from @wordpress/eslint-plugin@17.13.0
npm error     node_modules/@wordpress/eslint-plugin
npm error       @wordpress/eslint-plugin@"^17.5.0" from 10up-toolkit@6.4.1
npm error       node_modules/10up-toolkit
npm error       1 more (@10up/eslint-config)
npm error
npm error Conflicting peer dependency: @typescript-eslint/eslint-plugin@8.34.1
npm error node_modules/@typescript-eslint/eslint-plugin
npm error   peerOptional @typescript-eslint/eslint-plugin@"^8.0.0" from eslint-plugin-jest@29.0.1
npm error   node_modules/eslint-plugin-jest
npm error     peer eslint-plugin-jest@">=27.6.1" from @10up/eslint-config@4.1.2
npm error     node_modules/@10up/eslint-config
npm error       peer @10up/eslint-config@">=4.1.1" from 10up-toolkit@6.4.1
npm error       node_modules/10up-toolkit
npm error         10up-toolkit@"6.4.1" from the root project
npm error     peerOptional eslint-plugin-jest@">=25" from eslint-plugin-playwright@0.15.3
npm error     node_modules/eslint-plugin-playwright
npm error       eslint-plugin-playwright@"^0.15.3" from @wordpress/eslint-plugin@17.13.0
npm error       node_modules/@wordpress/eslint-plugin
npm error         @wordpress/eslint-plugin@"^17.5.0" from 10up-toolkit@6.4.1
npm error         node_modules/10up-toolkit
npm error         1 more (@10up/eslint-config)
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
```
</details>

**Comment by fabiankaegy** [comment]
@nicholasio wasn't this resolved with the last release?

**Comment by nicholasio** [comment]
The input buffer error is still happening however the issue described in https://github.com/10up/wp-scaffold/issues/290 has been fixed.

**Comment by Antonio-Laguna** [comment]
@nicholasio and @fabiankaegy I took some time to investigate. The issue happens because the images included aren't real images so they fail. Should I add a proper image (even if transparent) and/or add some notes around this?

**Comment by fabiankaegy** [comment]
@Antonio-Laguna for the other issues you've found I opened: https://github.com/10up/wp-scaffold/pull/293

I'd go ahead and add some actual images  👍

**Comment by fabiankaegy** [comment]
The image issue still persists. But I've fixed the other issues :)

**Comment by nicholasio** [comment]
It looks like the issue is that images get corrupted when scaffolding with init

**Comment by nicholasio** [comment]
Here's the fix: https://github.com/10up/10up-toolkit/pull/452
